// <auto-generated />
namespace Parliament.JargonBuster.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedCreatedByandUpdatedByfieldstoDefinitionItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedCreatedByandUpdatedByfieldstoDefinitionItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201605090727451_added CreatedBy and UpdatedBy fields to DefinitionItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
