namespace Parliament.JargonBuster.Core.Migrations
{
    using Domain;
    using Domain.Context;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<Parliament.JargonBuster.Core.Domain.Context.JargonBusterDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(JargonBusterDbContext context)
        {
            context.AlternateDefinitionItems.RemoveRange(context.AlternateDefinitionItems);
            context.Definitions.RemoveRange(context.Definitions);
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A Government policy document setting out plans for a future change in the law.", Phrase = "White Paper", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Proposal" }, new AlternateDefinitionItem { AlternateDefinition = "White Papers" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A policy document that is issued for early consultation and discussion.", Phrase = "Green Paper", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Consultation document" }, new AlternateDefinitionItem { AlternateDefinition = "feedback document" }, new AlternateDefinitionItem { AlternateDefinition = "Green Papers" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The senior ministerial team chosen by the Prime Minister who each lead on a specific area of government such as Health, Transport or Defence.", Phrase = "Cabinet", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Senior Ministers" }, new AlternateDefinitionItem { AlternateDefinition = "Departmental Heads" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Electoral systems that achieve a distribution of seats that is in line with the number of votes cast for each party.", Phrase = "Proportional representation" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Corridors to the left and right of the Chamber where MPs go to have their votes recorded when there is a division.", Phrase = "Aye and No Lobbies", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Voting corridors" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "An electoral system where the candidate that receives the most votes in each constituency is elected (used in UK General Elections).", Phrase = "First Past the Post" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The senior spokespeople chosen by the Leader of the Opposition to mirror the Cabinet in government and to lead for the Opposition on specific policy areas, such as Health or Transport.", Phrase = "Shadow Cabinet" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "An advisory body to the monarch made up of Cabinet members past and present, the Speaker, political party leaders and others.", Phrase = "Privy Counsellors", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Privy Council" }, new AlternateDefinitionItem { AlternateDefinition = "Advisors to the Monarch" }, new AlternateDefinitionItem { AlternateDefinition = "Privy Counsellor" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "MPs or members of the House of Lords who are not government ministers or Opposition spokespople.", Phrase = "Backbencher", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "backbench" }, new AlternateDefinitionItem { AlternateDefinition = "Backbenchers" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A Bill introduced under the ten minute rule which allows an MP ten minutes to make their case for a new Bill.", Phrase = "Ten Minute Rule Bill", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Short speech" }, new AlternateDefinitionItem { AlternateDefinition = "Ten Minute Rule Bills" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A practice ensuring major Government Bills mentioned in an election manifesto can move through the Lords.", Phrase = "Salisbury Doctrine" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A clause in a Bill that allows the Government to make future changes to it after it has become an Act wihout detailed scrutiny. ", Phrase = "Henry VIII clause", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Henry VIII Clauses" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A member of the House of Lords whose title and entitlement to sit in the Lords is not hereditary.", Phrase = "Life Peer", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Life Peers" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "An MP who acts as an assistant to a government minister but is not on the government payroll.", Phrase = "Parliamentary Private Secretary", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Minister's assistant" }, new AlternateDefinitionItem { AlternateDefinition = "Parliamentary Private Secretaries" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A procedure requiring the approval of both Houses of Parliament before a statutory instrument can become law.", Phrase = "Affirmative procedure" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The leader of the Government.", Phrase = "Prime Minister", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Government leader" }, new AlternateDefinitionItem { AlternateDefinition = "PM" }, new AlternateDefinitionItem { AlternateDefinition = "Prime Ministers" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Days that are set aside for debates on subjects chosen by the opposition (non-government) parties in the Commons.", Phrase = "Opposition days", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Opposition debate days" }, new AlternateDefinitionItem { AlternateDefinition = "Opposition Day" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Government ministers or Opposition spokespeople who sit at the front on each side of the Chamber.", Phrase = "frontbencher", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Frontbench" }, new AlternateDefinitionItem { AlternateDefinition = "Ministers and shadow ministers" }, new AlternateDefinitionItem { AlternateDefinition = "frontbenchers" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "An opportunity for people to meet with their local MP to raise issues or concerns.", Phrase = "Surgery", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "MP open meeting" }, new AlternateDefinitionItem { AlternateDefinition = "Surgeries" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A vote in parliament where MPs or members of the House of Lords are not put under pressure to vote in a particular way by their party.", Phrase = "Free vote", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Free Vote" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "", Phrase = "Lords Spiritual and Temporal" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A very senior office of state held by the member of the Cabinet who heads the Ministry of Justice.", Phrase = "Lord Chancellor" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A procedure for some statutory instruments in which they automatically become law after a certain number of days unless there is an objection from either House.", Phrase = "Negative procedure" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The MPs and members of the House of Lords who are in the Government.", Phrase = "Minister", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Members of Government" }, new AlternateDefinitionItem { AlternateDefinition = "Ministers" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "", Phrase = "Lord Chief Justice" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The written rules that govern how and when things are done in both Houses.", Phrase = "Standing Orders", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "House rules" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Boxes placed on either side of the table in the Chambers where Ministers and Shadow Ministers speak.", Phrase = "Despatch box", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Despatch Box" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A Bill that is judged by the Speaker to concern only taxation or public money and so cannot be amended or delayed by the House of Lords.", Phrase = "Money Bill", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "finance law proposals" }, new AlternateDefinitionItem { AlternateDefinition = "Money Bills" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A Bill that has been approved by both Houses of Parliament and has received Royal Assent becomes an Act of Parliament.", Phrase = "Act of Parliament", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "law" }, new AlternateDefinitionItem { AlternateDefinition = "Acts of Parliament" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A group of Conservative MPs that meet weekly to discuss and influence Party related issues.", Phrase = "The 1922 Committee (the 22)" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "An ornamental club that is the symbol of royal authority in each House.", Phrase = "The mace", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Ornamental club" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A declaration of loyalty to the monarch made by a new MP or member of the House of Lords before taking their seat.", Phrase = "Oath of Allegiance" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "", Phrase = "Commencement Orders" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "When two MPs of opposing parties agree not to vote if one MP has to be absent.", Phrase = "Pairing" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A proposed change to the text of a Bill or motion.", Phrase = "Amendment", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Amendments" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A member of the House of Lords.", Phrase = "Peer", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Member of the House of Lords" }, new AlternateDefinitionItem { AlternateDefinition = "Lord" }, new AlternateDefinitionItem { AlternateDefinition = "Baroness" }, new AlternateDefinitionItem { AlternateDefinition = "Peers" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Members appointed to verify the count and report the result back to the House when there is a division.", Phrase = "Teller", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Vote counters" }, new AlternateDefinitionItem { AlternateDefinition = "Tellers" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "", Phrase = "Presentation Bills" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A parliament with two assemblies, such as the UK which has the House of Commons and House of Lords.", Phrase = "Bicameral system", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Two chambers" }, new AlternateDefinitionItem { AlternateDefinition = "Two House system" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The monarch’s agreement to the making of a new law.", Phrase = "Royal Assent" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = " A procedure used by the government to timetable a Bill's progress through the House of Commons. ", Phrase = "Programme motion" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Members of the House of Lords that are non-party political.", Phrase = "Crossbench Peer", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Non-party political peers" }, new AlternateDefinitionItem { AlternateDefinition = "Crossbench" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "To allow another MP or member of the Lords to make an intervention during the course of a speech.", Phrase = "Give way", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Gave way" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Usually made up of the party that won the most seats in the general election, the government runs the country and is led by the Prime Minister.", Phrase = "Government" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The first speech made in the Chamber by a new member.", Phrase = "Maiden speech", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "First speech" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The red seat the Lord Speaker sits on in the House of Lords, made from wool from around the Commonwealth.", Phrase = "Woolsack" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A parliamentary year, normally beginning in spring and running for 12 months.", Phrase = "Session", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Parliamentary year" }, new AlternateDefinitionItem { AlternateDefinition = "Sessions" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A committee appointed to examine a Bill line-by-line in the Commons.", Phrase = "Public Bill Committee", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Public Bill Committees" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A plain English explanation of a Bill or amendment.", Phrase = "Explanatory Notes to Bill", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Plain English notes" }, new AlternateDefinitionItem { AlternateDefinition = "Notes" }, new AlternateDefinitionItem { AlternateDefinition = "Explanatory Notes to Bills" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Language that breaks the rules of politeness in the House of Commons Chamber and which will be asked to be withdrawn by the Speaker.", Phrase = "Unparliamentary language", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Impolite language " } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A percieved imbalance between voting rights for MPs from different nations following devolution.", Phrase = "West Lothian question" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A proposal for a new law or to change an existing law.", Phrase = "Bill", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Proposal for law" }, new AlternateDefinitionItem { AlternateDefinition = "Bills " } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A small group of senior members of the Church of England that sit in the House of Lords.", Phrase = "Bishops", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Bishop " } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The MP with the longest continuous record of service in the House of Commons.", Phrase = "Father of the House", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Fathers of the House" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A Cabinet Minister who heads a Government Department.", Phrase = "Secretary of State", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Head of Government Department" }, new AlternateDefinitionItem { AlternateDefinition = "Secretaries of State" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A Committee stage of a Bill that takes place in the Chamber so that all members can speak and vote.", Phrase = "Committee of the whole House" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Regulations made under the powers of an Act of Parliament.", Phrase = "Delegated legislation" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "To vote neither for nor against a proposal in a division.", Phrase = "Abstain", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Refuse to vote" }, new AlternateDefinitionItem { AlternateDefinition = "Abstained" }, new AlternateDefinitionItem { AlternateDefinition = "abstains" }, new AlternateDefinitionItem { AlternateDefinition = "abstaining" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The published set of policies that a Political Party stands for at an election.", Phrase = "Manifesto", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Manifestoes" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A vote where those in favour and against file through two separate lobbies and names are recorded and counted.", Phrase = "Divisions", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Vote" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "", Phrase = "Sewel Convention" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The special right of the House of Commons to decide public taxes and public spending.", Phrase = "Financial Privilege" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The to and fro of amendments to a Bill between the two Houses before a final version is agreed.", Phrase = "Ping-pong" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Financial assistance for Opposition parties in the House of Commons.", Phrase = "Short Money", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Opposition funding" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The short, half-hour debate held at the end of each day in the House of Commons.", Phrase = "Adjournment debates", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Final debate of the day" }, new AlternateDefinitionItem { AlternateDefinition = "Adjournment debate" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Term used to describe the other House in Parliament when in either of the Chambers.", Phrase = "Another place", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "The other House" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Bills introduced by individual MPs or members of the Lords rather than by the Government.", Phrase = "Private Members' Bills", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Backbench Bills" }, new AlternateDefinitionItem { AlternateDefinition = "Private Members' Bill " } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "An expiry date included in some laws allowing Parliament to take a second look after a fixed period.", Phrase = "Sunset clause", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Expiry date" }, new AlternateDefinitionItem { AlternateDefinition = "Sunset clauses " } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Appointed by each party in Parliament to organise business and enforce party discipline when required.", Phrase = "Whips", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Whip" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Procedure used to limit the debating time at a particular stage of a Bill in the House of Commons.", Phrase = "Allocation of time motions", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Allocation of time motion" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Weekly opportunity for MPs to ask the Prime Minister questions in the Commons, each Wednesday from 12pm.", Phrase = "Prime Minister's Question Time (PMQ's)" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Officially presenting a document to Parliament.", Phrase = "Laid papers", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Laying before Parliament" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Deputy Speakers assist the Speaker with their duties in the House of Commons and Lords.", Phrase = "Deputy Speakers" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Deliberately wasting time during a debate to prevent business from progressing.", Phrase = "Filibustering", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Filibuster" }, new AlternateDefinitionItem { AlternateDefinition = "filibustered" }, new AlternateDefinitionItem { AlternateDefinition = "filibustering" }, new AlternateDefinitionItem { AlternateDefinition = "filibusters" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Parliamentary questions put to a government minister in person in the Chamber.", Phrase = "Oral Question", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Oral Questions" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The official standards and rules of behaviour expected of MPs.", Phrase = "Code of Conduct for MPs" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Corridors to the left and right of the chamber where Lords go to vote yes (Content) or no (Not Content).", Phrase = "Content and Not Content Lobbies" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "An appeal to the Chair or Speaker for clarification or a ruling on a matter of procedure.", Phrase = "Point of order" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Rule that prevents MPs or Lords from referring to a current or impending court case.", Phrase = "Sub judice" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Delegation of governmental power.", Phrase = "Devolution" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The boundary beyond which guests or visitors may not pass when either House is sitting.", Phrase = "Bar of the House" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "", Phrase = "Parliamentary and Health Service Ombudsman" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Motions that are used to make a point or to attract the support of other MPs to a particular issue, event or campaign.", Phrase = "Early Day Motions (EDMs)", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Early Day Motion (EDM) " } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Official record of any business interests, extra paid work,  gifts etc that MPs and members of the Lords must declare.", Phrase = "Register of Members' Financial Interests" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "", Phrase = "Explanatory Memoranda" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Formal process in which an official is accused in the House of Commons of unlawful activity.", Phrase = "Impeachment" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Corridors that MPs and Lords file through to record their votes.", Phrase = "Division lobbies" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Proposal to let a Bill continue its progress in the next parliamentary session.", Phrase = "Carry-over motion/Bill", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Carry-over motions/Bills" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The individual paragraphs that make up a Bill and are numbered in sequence.", Phrase = "Clause", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Clauses" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Days allocated in House of Commons for the approval of spending by government departments and related debates.", Phrase = "Estimates days" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Formally put forward a question, motion or amendment in the House of Commons or the Lords.", Phrase = "Table (tabling)", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Tabled" }, new AlternateDefinitionItem { AlternateDefinition = "tabling" }, new AlternateDefinitionItem { AlternateDefinition = "tables " } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Term used to describe the discipling of an MP for breaking the rules of the House of Commons.", Phrase = "Naming of a Member" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Daily agenda of business in the House of Commons or the House of Lords.", Phrase = "Order Paper", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Order Papers" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Formal approval required before public money can be spent on something that hasn't previously been authorised.", Phrase = "Money resolutions" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Proposals to change to the law as it applies to the population in general.", Phrase = "Public Bill", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Public Bills" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The government's chief finance minister.", Phrase = "Chancellor of the Exchequer" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "The Government's general bank account at the Bank of England.", Phrase = "Consolidated Fund" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Official written report or everything that is said in the House of Commons and House of Lords Chambers.", Phrase = "Hansard", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = " Official Report" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "", Phrase = "Parliament" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "An MP elected by other MPs to act as chair and keep order during debates in the House of Commons.", Phrase = "The Speaker" });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Proposal to stop debating and make a decision on the matter being discussed.", Phrase = "Closure motion", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Closure motions" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "A question that requires a government minister to come to the House of Commons Chamber and give an immediate answer without prior notice.", Phrase = "Urgent Question", Alternates = new List<AlternateDefinitionItem> { new AlternateDefinitionItem { AlternateDefinition = "Urgent Question" } } });
            context.Definitions.AddOrUpdate(new DefinitionItem { Definition = "Language used in Parliament for some formal exchanges between the two Houses during the passage of a Bill through Parliament", Phrase = "Norman French" });

        }
    }
}
